sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#sonata_gallery_api:
#    resource: '@SonataMediaBundle/Controller/GalleryController.php'
#    prefix: /api/media/gallery
#    type: rest
#
#sonata_media_api:
#    resource: '@SonataMediaBundle/Controller/MediaController.php'
#    prefix: /api/media
#    type: rest
#
#sonata_media_api:
#    resource: '@SonataMediaBundle/Resources/config/routing/api.xml'
#    prefix: /api/media
#    type: rest
